[package]
name = "lang-test"
version = "0.1.0"
authors = ["Sampo Siitonen <sampo.siitonen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
